import { UUID } from 'crypto';

export type ProfileData = {
  id: number;
  created_at: string;
  recruited_by: UUID;
  date_promoted: string;
  date_joined: string;
  is_meritorious: boolean;
  in_game_name: string;
  dicord_name: string;
  rsi_id: string;
  mission_count: number;
  network_rank: {};
  recruitment_status: {};
  network_status: {};
  network_department: {};
  last_signed_in: string;
  network_ambassador: {};
  bravo_billet: {};
  has_read_rules: boolean;
  profile_providerId: string;
  is_fed_level: boolean;
  fed_stats: {};
  is_fleet_level: boolean;
  is_company_level: boolean;
  company_stats: {};
  is_wing_level: boolean;
  wing_stats: {};
  is_flight_level: boolean;
  flight_stats: {};
  is_ic: boolean;
  is_banned: boolean;
  is_beta_tester: boolean;
  patreon_sub_level: {};
  is_first_fifty: boolean;
  org_memberships: [];
};
